version: '3.6'
services:

  flask:
    build: .
    environment:
      FORECAST_API_KEY_1: ''
      FORECAST_ANALYTICS_KEY: ''
      APP_HOST: '0.0.0.0'
      APP_PORT: 5000
    ports:
      - '5000:5000'